source_files/colour_helper_functions.c File Reference
#include `../headers/cub3d.h`
Functions
int32_t ft_pixel (uint8_t r, uint8_t g, uint8_t b, uint8_t a)
Creates a pixel from the given colour values.
int32_t pixel_colour (mlx_image_t *image, int x, int y)
attemps to find the pixel at the given coordinates.
int32_t texture_pixel_colour (mlx_texture_t *image, int x, int y)
attemps to find the pixel at the given coordinates.
void modify_pixel (int x, int y, int32_t colour, t_data *data)
Modifies the pixel at the given coordinates.
Function Documentation
ft_pixel()
int32_t ft_pixel (uint8_t r, uint8_t g, uint8_t b, uint8_t a)
Creates a pixel from the given colour values.
Parameters
r The red value of the pixel.
g The green value of the pixel.
b The blue value of the pixel.
a The alpha value of the pixel.
Returns
int32_t Returns the colour in int32_t format.
Referenced by pixel_colour(), populate_data(), and texture_pixel_colour().
modify_pixel()
void modify_pixel (int x, int y, int32_t colour, t_data * data)
Modifies the pixel at the given coordinates.
Parameters
x The x coordinate of the pixel.
y The y coordinate of the pixel.
colour The colour to be set.
data Pointer to the data structure.
References s_data::image, and pixel_colour().
Referenced by draw_ray().
pixel_colour()
int32_t pixel_colour (mlx_image_t * image, int x, int y)
attemps to find the pixel at the given coordinates.
Parameters
image Pointer to the image structure.
x The x coordinate of the pixel.
y The y coordinate of the pixel.
Returns
int32_t Returns the colour of the pixel.
References DEFAULT_COLOUR, and ft_pixel().
Referenced by modify_pixel().
texture_pixel_colour()
int32_t texture_pixel_colour (mlx_texture_t * image, int x, int y)
attemps to find the pixel at the given coordinates.
Parameters
image Pointer to the texture structure.
x The x coordinate of the pixel.
y The y coordinate of the pixel.
References DEFAULT_COLOUR, and ft_pixel().
Referenced by draw_ray().