headers/cub3d.h File Reference
#include `../../../MLX42/include/MLX42/MLX42.h`
#include <unistd.h>
#include <fcntl.h>
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
#include `../other_libraries/libft/libft.h`
Classes
struct s_ray
struct s_map
struct s_player
struct s_data
struct s_parsing_data
Macros
#define WIDTH 1920
#define HEIGHT 1080
#define FOV 1.0471975512f
#define FAILURE 1
#define SUCCESS 0
#define WEST 3.1415926535898f
#define NORTH 1.57079632679f
#define EAST 0
#define SOUTH 4.71238898038f
#define MOVE_SPEED 3.0f
#define ROTATE_SPEED 0.2f
#define DEFAULT_COLOUR 0xFF000000
Typedefs
typedef struct s_ray t_ray
typedef struct s_map t_map
typedef struct s_player t_player
typedef struct s_data t_data
typedef struct s_parsing_data t_parsing_data
Enumerations
enum e_direction {
GO_FORWARDS
, GO_BACKWARDS
, STRAFE_LEFT
, STRAFE_RIGHT
,
TURN_LEFT
, TURN_RIGHT
 }
Functions
int check_arguments (int argc, char **argv, t_map *map)
void free_map_info (t_map *map)
int validate_map (t_map *map)
void free_array (char **arr)
int ft_err (char *str)
writes an error message to the standard error output.
void mlx_looping (t_data *data)
Main loop of the program.
int32_t ft_pixel (uint8_t r, uint8_t g, uint8_t b, uint8_t a)
Creates a pixel from the given colour values.
void calculate_ray (t_ray *ray, t_data *data)
Calculates the distance of the ray and the texture to use.
void player_controller (void *param)
Controls the player movement.
void key_press (mlx_key_data_t key_data, void *param)
Closes the window when the escape key is pressed.
void fix_fish_eye (t_ray *ray, t_data *data)
Fixes the fish eye effect.
void free_all_and_exit (t_data *data)
Frees all the allocated memory and exits the program.
int32_t texture_pixel_colour (mlx_texture_t *image, int x, int y)
attemps to find the pixel at the given coordinates.
void modify_pixel (int x, int y, int32_t colour, t_data *data)
Modifies the pixel at the given coordinates.
int parse_directions (t_map *map, char *line, int *count)
int parse_f (t_map *map, char *line, int *count)
int parse_c (t_map *map, char *line, int *count)
int check_lines (t_map *map)
int validate_floor (t_map *map)
int validate_ceiling (t_map *map)
int reformat_map (t_data *data)
reformats the map to a rectangle and into a 2D-array.
int open_load_textures (t_data *data)
Opens and loads the textures.
int check_islands (t_data *data)
Macro Definition Documentation
DEFAULT_COLOUR
#define DEFAULT_COLOUR 0xFF000000
EAST
#define EAST 0
FAILURE
#define FAILURE 1
FOV
#define FOV 1.0471975512f
HEIGHT
#define HEIGHT 1080
MOVE_SPEED
#define MOVE_SPEED 3.0f
NORTH
#define NORTH 1.57079632679f
ROTATE_SPEED
#define ROTATE_SPEED 0.2f
SOUTH
#define SOUTH 4.71238898038f
SUCCESS
#define SUCCESS 0
WEST
#define WEST 3.1415926535898f
WIDTH
#define WIDTH 1920
Typedef Documentation
t_data
typedef struct s_data t_data
t_map
typedef struct s_map t_map
t_parsing_data
typedef struct s_parsing_data t_parsing_data
t_player
typedef struct s_player t_player
t_ray
typedef struct s_ray t_ray
Enumeration Type Documentation
e_direction
enum e_direction
Enumerator
GO_FORWARDS
GO_BACKWARDS
STRAFE_LEFT
STRAFE_RIGHT
TURN_LEFT
TURN_RIGHT
Function Documentation
calculate_ray()
void calculate_ray (t_ray * ray, t_data * data)
Calculates the distance of the ray and the texture to use.
Parameters
ray Pointer to the ray structure.
data Pointer to the data structure.
References s_ray::angle, s_ray::distance, s_data::east_texture, horizontal_ray(), s_data::south_texture, s_ray::texture, vertical_ray(), s_ray::x, and s_ray::y.
Referenced by render_next_frame().
check_arguments()
int check_arguments (int argc, char ** argv, t_map * map)
Referenced by initial_map_validation().
check_islands()
int check_islands (t_data * data)
Referenced by reformat_map().
check_lines()
int check_lines (t_map * map)
fix_fish_eye()
void fix_fish_eye (t_ray * ray, t_data * data)
Fixes the fish eye effect.
Parameters
ray Pointer to the ray structure.
data Pointer to the data structure.
fish eye effect is caused
by the rays hitting the walls at an angle.
References s_ray::angle, s_ray::distance, s_data::player, and s_player::rotation_angle.
Referenced by render_next_frame().
free_all_and_exit()
void free_all_and_exit (t_data * data)
Frees all the allocated memory and exits the program.
Parameters
data Pointer to the data structure.
References s_data::east_texture, free_array(), free_map_info(), s_data::map, s_data::north_texture, s_data::parse_data, s_data::south_texture, and s_data::west_texture.
Referenced by init_mlx(), and mlx_looping().
free_array()
void free_array (char ** arr)
Referenced by free_all_and_exit(), and main().
free_map_info()
void free_map_info (t_map * map)
Referenced by free_all_and_exit(), initial_map_validation(), and main().
ft_err()
int ft_err (char * str)
writes an error message to the standard error output.
Parameters
str The error message to be written.
Returns
int Returns 1.
References FAILURE, and ft_strlen().
Referenced by init_mlx(), load_textures(), open_load_textures(), and reformat_map().
ft_pixel()
int32_t ft_pixel (uint8_t r, uint8_t g, uint8_t b, uint8_t a)
Creates a pixel from the given colour values.
Parameters
r The red value of the pixel.
g The green value of the pixel.
b The blue value of the pixel.
a The alpha value of the pixel.
Returns
int32_t Returns the colour in int32_t format.
Referenced by pixel_colour(), populate_data(), and texture_pixel_colour().
key_press()
void key_press (mlx_key_data_t key_data, void * param)
Closes the window when the escape key is pressed.
Parameters
key_data The key data.
param Pointer to the data structure.
References s_data::mlx.
Referenced by mlx_looping().
mlx_looping()
void mlx_looping (t_data * data)
Main loop of the program.
Parameters
data Pointer to the data structure.
References free_all_and_exit(), init_mlx(), key_press(), s_data::mlx, player_controller(), and render_next_frame().
Referenced by main().
modify_pixel()
void modify_pixel (int x, int y, int32_t colour, t_data * data)
Modifies the pixel at the given coordinates.
Parameters
x The x coordinate of the pixel.
y The y coordinate of the pixel.
colour The colour to be set.
data Pointer to the data structure.
References s_data::image, and pixel_colour().
Referenced by draw_ray().
open_load_textures()
int open_load_textures (t_data * data)
Opens and loads the textures.
Parameters
data Pointer to the data structure.
Returns
int Returns 0 if the textures are loaded successfully.
References s_map::ea, ft_err(), load_textures(), s_map::no, s_data::parse_data, s_map::so, and s_map::we.
Referenced by main().
parse_c()
int parse_c (t_map * map, char * line, int * count)
parse_directions()
int parse_directions (t_map * map, char * line, int * count)
parse_f()
int parse_f (t_map * map, char * line, int * count)
player_controller()
void player_controller (void * param)
Controls the player movement.
Parameters
param Pointer to the data structure.
References GO_BACKWARDS, GO_FORWARDS, s_data::mlx, move_player(), STRAFE_LEFT, STRAFE_RIGHT, TURN_LEFT, turn_player(), and TURN_RIGHT.
Referenced by mlx_looping().
reformat_map()
int reformat_map (t_data * data)
reformats the map to a rectangle and into a 2D-array.
Parameters
data Pointer to the data structure.
Returns
int Returns 0 if the map is reformatted successfully.
References check_islands(), ft_err(), ft_strlen(), s_map::line_count, s_data::map, s_data::map_height, s_data::map_width, s_data::parse_data, and realloc_line().
Referenced by main().
texture_pixel_colour()
int32_t texture_pixel_colour (mlx_texture_t * image, int x, int y)
attemps to find the pixel at the given coordinates.
Parameters
image Pointer to the texture structure.
x The x coordinate of the pixel.
y The y coordinate of the pixel.
References DEFAULT_COLOUR, and ft_pixel().
Referenced by draw_ray().
validate_ceiling()
int validate_ceiling (t_map * map)
validate_floor()
int validate_floor (t_map * map)
validate_map()
int validate_map (t_map * map)
Referenced by initial_map_validation().