other_libraries/libft/ft_lstmap_bonus.c File Reference
#include `libft.h`
Functions
t_list * ft_lstmap (t_list *lst, void *(f)(void *), void(*del)(void *))
Function Documentation
ft_lstmap()
t_list* ft_lstmap (t_list * lst, void * f)(void *, void(*)(void *) del)
References s_list::content, ft_lstadd_back(), ft_lstclear(), ft_lstnew(), and s_list::next.