other_libraries/libft/ft_memcpy.c File Reference
#include `libft.h`
Functions
void * ft_memcpy (void *dst, const void *src, size_t n)
Function Documentation
ft_memcpy()
void* ft_memcpy (void * dst, const void * src, size_t n)
Referenced by ft_strdup(), ft_strjoin(), ft_strndup(), and ft_substr().