other_libraries/libft/ft_strndup.c File Reference
this file contains the ft_strndup function.
#include `libft.h`
Functions
char * ft_strndup (const char *s, size_t n)
Duplicates a string up to n characters.
Detailed Description
this file contains the ft_strndup function.
Function Documentation
ft_strndup()
char* ft_strndup (const char * s, size_t n)
Duplicates a string up to n characters.
Parameters
s The string to be duplicated.
n The amount of characters to be duplicated.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), and ft_strlen().