other_libraries/libft/ft_strdup.c File Reference
this file contains the ft_strdup function.
#include `libft.h`
Functions
char * ft_strdup (const char *s)
Duplicates a string.
Detailed Description
this file contains the ft_strdup function.
Function Documentation
ft_strdup()
char* ft_strdup (const char * s)
Duplicates a string.
Parameters
s The string to be duplicated.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), and ft_strlen().
Referenced by ft_strjoin(), ft_substr(), and populate_data().