other_libraries/libft/ft_strjoin.c File Reference
this file contains the ft_strjoin function.
#include `libft.h`
Functions
char * ft_strjoin (char const *s1, char const *s2)
Joins two strings together.
Detailed Description
this file contains the ft_strjoin function.
Function Documentation
ft_strjoin()
char* ft_strjoin (char const * s1, char const * s2)
Joins two strings together.
Parameters
s1 The first string.
s2 The second string.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), ft_strdup(), and ft_strlen().