other_libraries/libft/ft_substr.c File Reference
this file contains the ft_substr function.
#include `libft.h`
Functions
char * ft_substr (char const *s, unsigned int start, size_t len)
Creates a substring from a string.
Detailed Description
this file contains the ft_substr function.
Function Documentation
ft_substr()
char* ft_substr (char const * s, unsigned int start, size_t len)
Creates a substring from a string.
Parameters
s The string to be copied.
start The starting index.
len The length of the substring.
Returns
The new substring.
References ft_calloc(), ft_memcpy(), ft_strdup(), and ft_strlen().