other_libraries/libft/ft_calloc.c File Reference
this file contains the ft_calloc function.
#include `libft.h`
Functions
void * ft_calloc (size_t count, size_t size)
Allocates memory for an pointer array and sets each element to zero.
Detailed Description
this file contains the ft_calloc function.
Function Documentation
ft_calloc()
void* ft_calloc (size_t count, size_t size)
Allocates memory for an pointer array and sets each element to zero.
Parameters
count The amount of elements in the array.
size The size of each element.
Returns
Returns a pointer to the allocated memory or returns NULL.
References ft_memset().
Referenced by ft_strdup(), ft_strjoin(), ft_strmapi(), ft_strndup(), ft_substr(), and realloc_line().