other_libraries/libft/get_next_line_utils.c File Reference
#include `libft.h`
Functions
char * gnl_strchr (char *s, int c)
size_t gnl_strlen (const char *s)
char * gnl_strjoin (char *s1, char *s2)
Function Documentation
gnl_strchr()
char* gnl_strchr (char * s, int c)
References gnl_strlen().
gnl_strjoin()
char* gnl_strjoin (char * s1, char * s2)
References gnl_strlen().
gnl_strlen()
size_t gnl_strlen (const char * s)
Referenced by gnl_strchr(), and gnl_strjoin().