source_files/helper_functions.c File Reference
#include `../headers/cub3d.h`
Functions
void free_all_and_exit (t_data *data)
Frees all the allocated memory and exits the program.
void fix_fish_eye (t_ray *ray, t_data *data)
Fixes the fish eye effect.
int ft_err (char *str)
writes an error message to the standard error output.
Function Documentation
fix_fish_eye()
void fix_fish_eye (t_ray * ray, t_data * data)
Fixes the fish eye effect.
Parameters
ray Pointer to the ray structure.
data Pointer to the data structure.
fish eye effect is caused
by the rays hitting the walls at an angle.
References s_ray::angle, s_ray::distance, s_data::player, and s_player::rotation_angle.
Referenced by render_next_frame().
free_all_and_exit()
void free_all_and_exit (t_data * data)
Frees all the allocated memory and exits the program.
Parameters
data Pointer to the data structure.
References s_data::east_texture, free_array(), free_map_info(), s_data::map, s_data::north_texture, s_data::parse_data, s_data::south_texture, and s_data::west_texture.
Referenced by init_mlx(), and mlx_looping().
ft_err()
int ft_err (char * str)
writes an error message to the standard error output.
Parameters
str The error message to be written.
Returns
int Returns 1.
References FAILURE, and ft_strlen().
Referenced by init_mlx(), load_textures(), open_load_textures(), and reformat_map().