source_files/initiate_mlx.c File Reference
#include `../headers/cub3d.h`
Functions
void init_mlx (t_data *data)
Initializes the mlx library stuff.
void figure_out_texture (int *texture_height, t_ray *ray, t_data *data)
Figures out what texture to use and how to draw it.
void draw_ray (t_ray *ray, int texture_height, int rays_amount, t_data *data)
Draws the ray on the screen.
void render_next_frame (void *main_data)
Renders the next frame of the game.
void mlx_looping (t_data *data)
Main loop of the program.
Function Documentation
draw_ray()
void draw_ray (t_ray * ray, int texture_height, int rays_amount, t_data * data)
Draws the ray on the screen.
Parameters
ray Pointer to the ray structure.
texture_height Height of the texture.
rays_amount Amount of rays.
data Pointer to the data structure.
References s_data::ceiling_colour, s_ray::distance, s_data::floor_colour, HEIGHT, modify_pixel(), s_ray::texture, texture_pixel_colour(), s_ray::x, and s_ray::y.
Referenced by render_next_frame().
figure_out_texture()
void figure_out_texture (int * texture_height, t_ray * ray, t_data * data)
Figures out what texture to use and how to draw it.
Parameters
texture_height Pointer to the height of the texture.
ray Pointer to the ray structure.
data Pointer to the data structure.
References s_ray::angle, s_ray::distance, s_data::east_texture, HEIGHT, NORTH, s_data::north_texture, SOUTH, s_data::south_texture, s_ray::texture, WEST, s_data::west_texture, s_ray::x, and s_ray::y.
Referenced by render_next_frame().
init_mlx()
void init_mlx (t_data * data)
Initializes the mlx library stuff.
Parameters
data Pointer to the data structure.
References FALSE, free_all_and_exit(), ft_err(), HEIGHT, s_data::image, s_data::mlx, and WIDTH.
Referenced by mlx_looping().
mlx_looping()
void mlx_looping (t_data * data)
Main loop of the program.
Parameters
data Pointer to the data structure.
References free_all_and_exit(), init_mlx(), key_press(), s_data::mlx, player_controller(), and render_next_frame().
Referenced by main().
render_next_frame()
void render_next_frame (void * main_data)
Renders the next frame of the game.
Parameters
main_data Pointer to the data structure.
function is called by mlx_loop_hook
to render the next frame of the game.
References s_ray::angle, calculate_ray(), s_ray::distance, draw_ray(), figure_out_texture(), fix_fish_eye(), FOV, HEIGHT, s_data::player, s_player::rotation_angle, and WIDTH.
Referenced by mlx_looping().