other_libraries/libft/libft.h File Reference
#include <stdlib.h>
#include <unistd.h>
#include <stdarg.h>
#include `vector.h`
Classes
struct s_list
struct s_hash_table
Macros
#define BUFFER_SIZE 42
Typedefs
typedef struct s_list t_list
typedef struct s_hash_table t_hash
Functions
int ft_atoi (const char *str)
Converts the initial portion of the string pointed to by str to int.
void ft_bzero (void *s, size_t n)
Writes n zeroed bytes to the string s.
void * ft_calloc (size_t count, size_t size)
Allocates memory for an pointer array and sets each element to zero.
int ft_isalnum (int c)
Tests for any character for which isalpha or isdigit is true.
int ft_isalpha (int c)
Tests for any character for which isupper or islower is true.
int ft_isascii (int c)
int ft_isdigit (int c)
int ft_isprint (int c)
void * ft_memchr (const void *s, int c, size_t n)
int ft_memcmp (const void *s1, const void *s2, size_t n)
void * ft_memcpy (void *dst, const void *src, size_t n)
void * ft_memmove (void *dst, const void *src, size_t len)
void * ft_memset (void *b, int c, size_t len)
Writes len bytes of value c to the string b.
char * ft_strchr (const char *s, int c)
char * ft_strdup (const char *s)
Duplicates a string.
size_t ft_strlcat (char *dst, const char *src, size_t dstsize)
size_t ft_strlcpy (char *dst, const char *src, size_t dstsize)
Copies a string to a buffer.
size_t ft_strlen (const char *s)
Finds the length of a string.
int ft_strncmp (const char *s1, const char *s2, size_t n)
Compares two strings.
char * ft_strnstr (const char *haystack, const char *needle, size_t len)
char * ft_strrchr (const char *s, int c)
char ft_tolower (char c)
char ft_toupper (char c)
char * ft_substr (char const *s, unsigned int start, size_t len)
Creates a substring from a string.
char * ft_strjoin (char const *s1, char const *s2)
Joins two strings together.
char * ft_strtrim (char const *s1, char const *set)
Trims the set of characters from the beginning and end of a string.
char ** ft_split (char const *s, char c)
Splits a string into substrings using a delimiter.
char * ft_itoa (int n)
Converts an integer to a string.
char * ft_strmapi (char const *s, char(*f)(unsigned int, char))
Applies a function to each character of a string.
void ft_striteri (char *s, void(*f)(unsigned int, char *))
void ft_putchar_fd (char c, int fd)
void ft_putstr_fd (char *s, int fd)
Outputs a string to a file descriptor.
void ft_putendl_fd (char *s, int fd)
Outputs a string to a file descriptor followed by a newline.
void ft_putnbr_fd (int n, int fd)
Outputs an integer to a file descriptor.
t_list * ft_lstnew (void *content)
void ft_lstadd_front (t_list **lst, t_list *new)
int ft_lstsize (t_list *lst)
t_list * ft_lstlast (t_list *lst)
void ft_lstadd_back (t_list **lst, t_list *new)
void ft_lstdelone (t_list *lst, void(*del)(void *))
void ft_lstclear (t_list **lst, void(*del)(void *))
void ft_lstiter (t_list *lst, void(*f)(void *))
t_list * ft_lstmap (t_list *lst, void *(f)(void *), void(*del)(void *))
int ft_puthex (unsigned int nbr, int uppercase, int *length)
int ft_ptrhex (unsigned long ptr, int *length)
int ft_putstr (char *string)
int ft_put_u_nbr (unsigned int n, int *length)
int ft_putchar (char c)
int ft_putnbr (int n, int *length)
int ft_printf (const char *str,...)
Custom printf function.
void ft_free_substrings (char ***arr_str)
Frees the substrings of a string array.
int ft_strcmp (char *s1, char *s2)
Compares two strings.
char * ft_strndup (const char *s, size_t n)
Duplicates a string up to n characters.
char * gnl_strchr (char *s, int c)
size_t gnl_strlen (const char *s)
char * gnl_strjoin (char *s1, char *s2)
char * get_next_line (int fd)
unsigned long create_hash (unsigned char *str)
Creates a hash value from a string via djb2 method.
int insert_hash (t_hash *hash_table, char *key, int table_size)
t_hash * search_hash (t_hash *hash_table, char *key, int table_size)
Macro Definition Documentation
BUFFER_SIZE
#define BUFFER_SIZE 42
Typedef Documentation
t_hash
typedef struct s_hash_table t_hash
t_list
typedef struct s_list t_list
Function Documentation
create_hash()
unsigned long create_hash (unsigned char * str)
Creates a hash value from a string via djb2 method.
Parameters
str The string to be hashed.
Returns
The hash value.
Referenced by insert_hash(), and search_hash().
ft_atoi()
int ft_atoi (const char * str)
Converts the initial portion of the string pointed to by str to int.
Parameters
str The string to be converted.
Returns
Returns the converted int value.
Referenced by populate_data().
ft_bzero()
void ft_bzero (void * s, size_t n)
Writes n zeroed bytes to the string s.
Parameters
s The string to be zeroed.
n The amount of bytes to be zeroed.
Returns
void
References ft_memset().
ft_calloc()
void* ft_calloc (size_t count, size_t size)
Allocates memory for an pointer array and sets each element to zero.
Parameters
count The amount of elements in the array.
size The size of each element.
Returns
Returns a pointer to the allocated memory or returns NULL.
References ft_memset().
Referenced by ft_strdup(), ft_strjoin(), ft_strmapi(), ft_strndup(), ft_substr(), and realloc_line().
ft_free_substrings()
void ft_free_substrings (char *** arr_str)
Frees the substrings of a string array.
Parameters
arr_str The string array to be freed.
Returns
void
ft_isalnum()
int ft_isalnum (int c)
Tests for any character for which isalpha or isdigit is true.
Parameters
c The character to test.
Returns
Non-zero if the character tests true, zero if false.
References ft_isalpha(), and ft_isdigit().
ft_isalpha()
int ft_isalpha (int c)
Tests for any character for which isupper or islower is true.
Parameters
c The character to test.
Returns
Non-zero if the character tests true, zero if false.
Referenced by ft_isalnum().
ft_isascii()
int ft_isascii (int c)
ft_isdigit()
int ft_isdigit (int c)
Referenced by ft_isalnum().
ft_isprint()
int ft_isprint (int c)
ft_itoa()
char* ft_itoa (int n)
Converts an integer to a string.
Parameters
n The integer to be converted.
Returns
The string representation of the integer.
ft_lstadd_back()
void ft_lstadd_back (t_list ** lst, t_list * new)
References s_list::next.
Referenced by ft_lstmap().
ft_lstadd_front()
void ft_lstadd_front (t_list ** lst, t_list * new)
ft_lstclear()
void ft_lstclear (t_list ** lst, void(*)(void *) del)
References s_list::next.
Referenced by ft_lstmap().
ft_lstdelone()
void ft_lstdelone (t_list * lst, void(*)(void *) del)
References s_list::content.
ft_lstiter()
void ft_lstiter (t_list * lst, void(*)(void *) f)
References s_list::content, and s_list::next.
ft_lstlast()
t_list* ft_lstlast (t_list * lst)
References s_list::next.
ft_lstmap()
t_list* ft_lstmap (t_list * lst, void * f)(void *, void(*)(void *) del)
References s_list::content, ft_lstadd_back(), ft_lstclear(), ft_lstnew(), and s_list::next.
ft_lstnew()
t_list* ft_lstnew (void * content)
References s_list::content, and s_list::next.
Referenced by ft_lstmap().
ft_lstsize()
int ft_lstsize (t_list * lst)
References s_list::next.
ft_memchr()
void* ft_memchr (const void * s, int c, size_t n)
ft_memcmp()
int ft_memcmp (const void * s1, const void * s2, size_t n)
ft_memcpy()
void* ft_memcpy (void * dst, const void * src, size_t n)
Referenced by ft_strdup(), ft_strjoin(), ft_strndup(), and ft_substr().
ft_memmove()
void* ft_memmove (void * dst, const void * src, size_t len)
Referenced by vec_push(), and vec_resize().
ft_memset()
void* ft_memset (void * b, int c, size_t len)
Writes len bytes of value c to the string b.
Parameters
b The string to be written to.
c The value to be written.
len The amount of bytes to be written.
Returns
Returns a pointer to the memory area b.
Referenced by ft_bzero(), and ft_calloc().
ft_printf()
int ft_printf (const char * str, ...)
Custom printf function.
Parameters
str The string to be printed.
... The variadric arguments.
Returns
Returns the length of the printed string.
ft_ptrhex()
int ft_ptrhex (unsigned long ptr, int * length)
ft_put_u_nbr()
int ft_put_u_nbr (unsigned int n, int * length)
ft_putchar()
int ft_putchar (char c)
Referenced by ft_putstr().
ft_putchar_fd()
void ft_putchar_fd (char c, int fd)
ft_putendl_fd()
void ft_putendl_fd (char * s, int fd)
Outputs a string to a file descriptor followed by a newline.
Parameters
s The string to be outputted.
fd The file descriptor to be used.
References ft_strlen().
ft_puthex()
int ft_puthex (unsigned int nbr, int uppercase, int * length)
ft_putnbr()
int ft_putnbr (int n, int * length)
ft_putnbr_fd()
void ft_putnbr_fd (int n, int fd)
Outputs an integer to a file descriptor.
Parameters
n The integer to be outputted.
fd The file descriptor to be used.
ft_putstr()
int ft_putstr (char * string)
References ft_putchar().
ft_putstr_fd()
void ft_putstr_fd (char * s, int fd)
Outputs a string to a file descriptor.
Parameters
s The string to be outputted.
fd The file descriptor to be used.
References ft_strlen().
ft_split()
char** ft_split (char const * s, char c)
Splits a string into substrings using a delimiter.
Parameters
s The string to be split.
c The delimiter character.
Returns
The result array.
ft_strchr()
char* ft_strchr (const char * s, int c)
Referenced by find_collision().
ft_strcmp()
int ft_strcmp (char * s1, char * s2)
Compares two strings.
Parameters
s1 The first string to be compared.
s2 The second string to be compared.
Returns
Returns the difference between the two strings.
ft_strdup()
char* ft_strdup (const char * s)
Duplicates a string.
Parameters
s The string to be duplicated.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), and ft_strlen().
Referenced by ft_strjoin(), ft_substr(), and populate_data().
ft_striteri()
void ft_striteri (char * s, void(*)(unsigned int, char *) f)
ft_strjoin()
char* ft_strjoin (char const * s1, char const * s2)
Joins two strings together.
Parameters
s1 The first string.
s2 The second string.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), ft_strdup(), and ft_strlen().
ft_strlcat()
size_t ft_strlcat (char * dst, const char * src, size_t dstsize)
References ft_strlen().
ft_strlcpy()
size_t ft_strlcpy (char * dst, const char * src, size_t dstsize)
Copies a string to a buffer.
Parameters
dst The destination buffer.
src The source string.
dstsize The size of the destination buffer.
Returns
Returns the length of the source string.
References ft_strlen().
ft_strlen()
size_t ft_strlen (const char * s)
Finds the length of a string.
Parameters
s The string to be measured.
Returns
Returns the length of the string.
Referenced by ft_err(), ft_putendl_fd(), ft_putstr_fd(), ft_strdup(), ft_strjoin(), ft_strlcat(), ft_strlcpy(), ft_strmapi(), ft_strndup(), ft_strnstr(), ft_strrchr(), ft_substr(), and reformat_map().
ft_strmapi()
char* ft_strmapi (char const * s, char(*)(unsigned int, char) f)
Applies a function to each character of a string.
Parameters
s The string to be iterated.
f The function to be applied.
Returns
The new string.
References ft_calloc(), and ft_strlen().
ft_strncmp()
int ft_strncmp (const char * s1, const char * s2, size_t n)
Compares two strings.
Parameters
s1 The first string to be compared.
s2 The second string to be compared.
n The amount of characters to be compared.
Returns
Returns the difference between the first differing characters.
Referenced by ft_strnstr().
ft_strndup()
char* ft_strndup (const char * s, size_t n)
Duplicates a string up to n characters.
Parameters
s The string to be duplicated.
n The amount of characters to be duplicated.
Returns
Returns a pointer to the new string or returns NULL.
References ft_calloc(), ft_memcpy(), and ft_strlen().
ft_strnstr()
char* ft_strnstr (const char * haystack, const char * needle, size_t len)
References ft_strlen(), and ft_strncmp().
ft_strrchr()
char* ft_strrchr (const char * s, int c)
References ft_strlen().
ft_strtrim()
char* ft_strtrim (char const * s1, char const * set)
Trims the set of characters from the beginning and end of a string.
Parameters
s1 The string to be trimmed.
set The set of characters to be trimmed.
Returns
The new trimmed string.
ft_substr()
char* ft_substr (char const * s, unsigned int start, size_t len)
Creates a substring from a string.
Parameters
s The string to be copied.
start The starting index.
len The length of the substring.
Returns
The new substring.
References ft_calloc(), ft_memcpy(), ft_strdup(), and ft_strlen().
ft_tolower()
char ft_tolower (char c)
ft_toupper()
char ft_toupper (char c)
get_next_line()
char* get_next_line (int fd)
References BUFFER_SIZE.
gnl_strchr()
char* gnl_strchr (char * s, int c)
References gnl_strlen().
gnl_strjoin()
char* gnl_strjoin (char * s1, char * s2)
References gnl_strlen().
gnl_strlen()
size_t gnl_strlen (const char * s)
Referenced by gnl_strchr(), and gnl_strjoin().
insert_hash()
int insert_hash (t_hash * hash_table, char * key, int table_size)
References create_hash().
search_hash()
t_hash* search_hash (t_hash * hash_table, char * key, int table_size)
References create_hash().