source_files/load_data_functions.c File Reference
#include `../headers/cub3d.h`
Functions
void set_empty_data (int *len, int max_len, char *ptr1)
sets the rest of the data to spaces.
int realloc_line (char **ptr, int max_len)
int reformat_map (t_data *data)
reformats the map to a rectangle and into a 2D-array.
int load_textures (t_data *data)
Loads the images into textures.
int open_load_textures (t_data *data)
Opens and loads the textures.
Function Documentation
load_textures()
int load_textures (t_data * data)
Loads the images into textures.
Parameters
data Pointer to the data structure.
Returns
int Returns 0 if the textures are loaded successfully.
References s_map::ea, s_data::east_texture, ft_err(), s_map::no, s_data::north_texture, s_data::parse_data, s_map::so, s_data::south_texture, s_map::we, and s_data::west_texture.
Referenced by open_load_textures().
open_load_textures()
int open_load_textures (t_data * data)
Opens and loads the textures.
Parameters
data Pointer to the data structure.
Returns
int Returns 0 if the textures are loaded successfully.
References s_map::ea, ft_err(), load_textures(), s_map::no, s_data::parse_data, s_map::so, and s_map::we.
Referenced by main().
realloc_line()
int realloc_line (char ** ptr, int max_len)
@reallocates the line to the max_len.
Parameters
ptr Pointer to the line.
max_len The maximum length of the line.
Returns
int Returns 0 if the line is reallocated successfully.
References ft_calloc(), and set_empty_data().
Referenced by reformat_map().
reformat_map()
int reformat_map (t_data * data)
reformats the map to a rectangle and into a 2D-array.
Parameters
data Pointer to the data structure.
Returns
int Returns 0 if the map is reformatted successfully.
References check_islands(), ft_err(), ft_strlen(), s_map::line_count, s_data::map, s_data::map_height, s_data::map_width, s_data::parse_data, and realloc_line().
Referenced by main().
set_empty_data()
void set_empty_data (int * len, int max_len, char * ptr1)
sets the rest of the data to spaces.
Parameters
len Pointer to the length of the line.
max_len The maximum length of the line.
ptr1 Pointer to the line.
Referenced by realloc_line().