source_files/player_control.c File Reference
#include `../headers/cub3d.h`
Functions
void key_press (mlx_key_data_t key_data, void *param)
Closes the window when the escape key is pressed.
void move_player (t_data *data, enum e_direction direction)
Moves the player.
void turn_player (t_data *data, enum e_direction direction)
Turns the player.
void player_controller (void *param)
Controls the player movement.
Function Documentation
key_press()
void key_press (mlx_key_data_t key_data, void * param)
Closes the window when the escape key is pressed.
Parameters
key_data The key data.
param Pointer to the data structure.
References s_data::mlx.
Referenced by mlx_looping().
move_player()
void move_player (t_data * data, enum e_direction direction)
Moves the player.
Parameters
data Pointer to the data structure.
direction The direction to move.
References GO_BACKWARDS, GO_FORWARDS, MOVE_SPEED, s_data::player, s_player::rotation_angle, STRAFE_LEFT, s_player::x, and s_player::y.
Referenced by player_controller().
player_controller()
void player_controller (void * param)
Controls the player movement.
Parameters
param Pointer to the data structure.
References GO_BACKWARDS, GO_FORWARDS, s_data::mlx, move_player(), STRAFE_LEFT, STRAFE_RIGHT, TURN_LEFT, turn_player(), and TURN_RIGHT.
Referenced by mlx_looping().
turn_player()
void turn_player (t_data * data, enum e_direction direction)
Turns the player.
Parameters
data Pointer to the data structure.
direction The direction to turn.
References s_data::player, ROTATE_SPEED, s_player::rotation_angle, TURN_LEFT, and TURN_RIGHT.
Referenced by player_controller().