source_files/ray_calculations.c File Reference
#include `../headers/cub3d.h`
Functions
void find_collision (t_ray *ray, float x_travel, float y_travel, t_data *data)
float horizontal_ray (t_ray *ray, float angle, t_data *data)
float vertical_ray (t_ray *ray, float angle, t_data *data)
void calculate_ray (t_ray *ray, t_data *data)
Function Documentation
calculate_ray()
void calculate_ray (t_ray * ray, t_data * data)
References s_ray::angle, s_ray::distance, s_data::east_texture, horizontal_ray(), s_data::south_texture, s_ray::texture, vertical_ray(), s_ray::x, and s_ray::y.
Referenced by render_next_frame().
find_collision()
void find_collision (t_ray * ray, float x_travel, float y_travel, t_data * data)
References ft_strchr(), s_data::map, s_data::map_height, s_data::map_width, s_ray::x, and s_ray::y.
Referenced by horizontal_ray(), and vertical_ray().
horizontal_ray()
float horizontal_ray (t_ray * ray, float angle, t_data * data)
References find_collision(), s_data::player, WEST, s_ray::x, s_player::x, s_ray::y, and s_player::y.
Referenced by calculate_ray().
vertical_ray()
float vertical_ray (t_ray * ray, float angle, t_data * data)
References find_collision(), s_data::player, SOUTH, s_ray::x, s_player::x, s_ray::y, and s_player::y.
Referenced by calculate_ray().