other_libraries/libft/vector.h File Reference
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <stdbool.h>
#include <stdio.h>
Classes
struct s_vec
Macros
#define TRUE 1
#define FALSE 0
Typedefs
typedef struct s_vec t_vec
Functions
int vec_new (t_vec *src, size_t init_len, size_t elem_size)
void vec_free (t_vec *src)
int vec_resize (t_vec *src, size_t target_len)
int vec_push (t_vec *src, void *elem)
void * vec_get (t_vec *src, size_t index)
Macro Definition Documentation
FALSE
#define FALSE 0
TRUE
#define TRUE 1
Typedef Documentation
t_vec
typedef struct s_vec t_vec
Function Documentation
vec_free()
void vec_free (t_vec * src)
References s_vec::alloc_size, s_vec::elem_size, s_vec::len, and s_vec::memory.
vec_get()
void* vec_get (t_vec * src, size_t index)
References s_vec::elem_size, s_vec::len, and s_vec::memory.
Referenced by populate_data().
vec_new()
int vec_new (t_vec * src, size_t init_len, size_t elem_size)
References s_vec::alloc_size, s_vec::elem_size, s_vec::len, and s_vec::memory.
Referenced by initial_map_validation(), vec_push(), and vec_resize().
vec_push()
int vec_push (t_vec * src, void * elem)
References s_vec::alloc_size, s_vec::elem_size, ft_memmove(), s_vec::len, s_vec::memory, vec_new(), and vec_resize().
vec_resize()
int vec_resize (t_vec * src, size_t target_len)
References s_vec::alloc_size, s_vec::elem_size, ft_memmove(), s_vec::len, s_vec::memory, and vec_new().
Referenced by vec_push().